### ISSUE TITLE
Criar o Bloc do Carrinho

### ISSUE THREAD

**Issue by Bwolfs2** [Flutterando/carrinho_compras#10]
- [x] Criar o Bloc do Carrinho
    - [x]  Obter Produtos do Carrinho
    - [x] Adicionar Produto no Carrinho
    - [x] Remover Produto do Carrinho

**Comment by jacobaraujo7** [comment]
Eu vi que o check-list já esta completo.
Essa branch já pode ser testada?

**Comment by Bwolfs2** [comment]
Ainda não, estou com uma duvida, onde deixar os dados do carrinho?

**Comment by jacobaraujo7** [comment]
no caso, os dados vão ser consumido pela pessoa que for construir a tela do carrinho de compras.
Você pode realizar testes unitários para verificar se as funcionalidades pedidas foram alcançadas.
