### ISSUE TITLE
Tela do Carrinho de Compras

### ISSUE THREAD

**Issue by Bwolfs2** [Flutterando/carrinho_compras#5]
- [x] O Acesso a tela do carrinho deve ser feito ao tocar no FloatActionButton da ProdutosPage.
- [x]  Listar os produtos que foram incluídos. BLoC Carrinho #10 
- [x]  Colocar um botão para excluir o produto
- [x]  Colocar um botão para Finalizar a compra

O card deve conter Título, Descrição e Preço

#10 Bloc
#9 Repository

**Comment by Bwolfnoob** [comment]
Criar a tela de carrinho de comprar.
Mostrar os produtos que foram incluidos.
Um botão para excluir o produto
Um botão para Salvar

**Comment by jacobaraujo7** [comment]
onde que os produtos são incluidos?
