### ISSUE TITLE
JSON com Array com produtos

### ISSUE THREAD

**Issue by Bwolfs2** [Flutterando/carrinho_compras#7]
Criar um json contendo dados de produtos.
Cada objeto do array deve conter:
{
   id: int
   title: String
   prince: long
   description: String        
   image: String      
}

- [x] Criar json na path  backend/products.json.
- [x] Disponibilizar link de acesso funcional.

**Comment by Bwolfs2** [comment]
https://raw.githubusercontent.com/Flutterando/carrinho_compras/master/app/lib/src/backend/products.json

**Comment by jacobaraujo7** [comment]
A Issue é clara, pede um back de produtos alimentícios e tem smartphones. Favor, altere o tipo de produto ou peça para o criador da issue alterar o tipo de produto que deve conter no json.

**Comment by Bwolfs2** [comment]
https://raw.githubusercontent.com/Flutterando/carrinho_compras/master/backend/products.json
